# Fly.io app configuration for Vyntix.ts
app = "vyntix-ts"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"  # ✅ Fly.io のポートを Next.js に合わせる

[http_service]
  internal_port = 3000  # ✅ Next.js は 3000 番ポート
  force_https = true
  auto_stop_machines = false  # ✅ これを無効にする
  auto_start_machines = true
  min_machines_running = 1  # ✅ 最低1つは常に起動
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

